### ISSUE TITLE
Script can not scan audio files at path contain "Assets" string

### ISSUE THREAD

**Issue by giangchau92** [CarterGames/AudioManager#2]
Hi,

I encountered a minor issue with the script that I wanted to bring to your attention.
In my folder structure, I have organized my files in the following way:
```
Assets/PingPong/Script/*
Assets/PingPong/Assets/Prefabs/*
Assets/PingPong/Assets/Audio/*
Assets/PingPong/Assets/Dialog/*
```
I noticed that in the source code, the line`fileDirs.GetArrayElementAtIndex(i).stringValue.Replace("Assets", ""))` could work incorrectly in this case, script can not scan audio clip.

Thank you for creating such a useful asset

**Comment by JonathanMCarter** [comment]
Only just realised I never responded to this issue, my bad. Yea this is a bit of a flaw, but with a new version coming later in the year with a different scanning system the issue won't be an issue in that new version. So, this will likely not be fixed as it is easily avoidable.
